require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { GoogleGenAI } = require('@google/genai');

const app = express();
app.use(cors());
app.use(express.json());

// Serve static frontend files
app.use(express.static('./'));

// Initialize Gemini SDK with API key from environment
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// Chat API endpoint
app.post('/chat', async (req, res) => {
  try {
    const userMessage = req.body.message;

    if (!userMessage) {
      return res.status(400).json({ reply: "❌ Please type a valid message." });
    }

    if (!process.env.GEMINI_API_KEY) {
      return res.json({ reply: "❌ API Key missing in Render Environment Variables!" });
    }

    // Updated model name to gemini-2.5-flash
    const response = await ai.models.generateContent({
      model: 'gemini-3.6-flash',
      contents: userMessage,
    });

    const replyText = response.text;

    if (replyText) {
      res.json({ reply: replyText });
    } else {
      res.json({ reply: "❌ No text generated by Gemini API." });
    }

  } catch (error) {
    console.error("API Error Details:", error);
    res.json({ reply: `❌ Error from Gemini: ${error.message || JSON.stringify(error)}` });
  }
});

// Dynamic port for Render
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
});
